### ISSUE TITLE
Redis configuration and cache

### ISSUE THREAD

**Issue by noindie** [fballiano/docker-magento2#1]
Hello!
I've enabled redis for magento's cache, with your settings, but here's my problem: my cms content keeps being cached. I've tried with a "redish-cli flushall" on redis container but did not work.
And flushing cache via magento admin didn't work too. 

Thanks

**Comment by fballiano** [comment]
Hi, could it be a varnish related issue more than a redis one?

**Comment by noindie** [comment]
yes, you're right.
I solved by changing default TTL for public content in admin backend and restarting varnish container.
Thanks

**Comment by fballiano** [comment]
;-)
