### ISSUE TITLE
Debian 9

### ISSUE THREAD

**Issue by kauansoft** [fballiano/docker-magento2#13]
Hello, im using a fresh installation of debian 9.

Got this error:
` Fatal error: Uncaught Magento\Framework\Exception\FileSystemException: The file "/var/www/html/var/.regenerate" cannot be deleted Warning!unlink(/var/www/html/var/.regenerate): Permission denied in /var/www/html/vendor/magento/framework/Filesystem/Driver/File.php:382 Stack trace: #0 /var/www/html/vendor/magento/framework/Filesystem/Directory/Write.php(172): Magento\Framework\Filesystem\Driver\File->deleteFile('/var/www/html/v...') #1 /var/www/html/vendor/magento/framework/Code/GeneratedFiles.php(99): Magento\Framework\Filesystem\Directory\Write->delete('/var/.regenerat...') #2 /var/www/html/vendor/magento/framework/App/ObjectManagerFactory.php(110): Magento\Framework\Code\GeneratedFiles->cleanGeneratedFiles() #3 /var/www/html/vendor/magento/framework/App/Bootstrap.php(208): Magento\Framework\App\ObjectManagerFactory->create(Array) #4 /var/www/html/vendor/magento/framework/App/Bootstrap.php(123): Magento\Framework\App\Bootstrap->__construct(Object(Magento\Framework\App\ObjectManagerFactory), '/var/www/html', Array) #5 /var in /var/www/html/vendor/magento/framework/Filesystem/Driver/File.php on line 382`

This path /var/www/html/vendor/magento/... doesn't exist, i use docker compose on /home/magento/
and the magento files are inside (/home/magento/magento2). But i forced the installation (myip/setup) it worked, but got same error when i try acesss my site. (Admin page is working /admin)

**Comment by kauanguesser** [comment]
Others pages are working, like account, login/signup, search...

**Comment by fballiano** [comment]
mmm seems to be a permission problem, did you "chmod -R 777" your magento2/var directory?

I know it's the classical "did you plug the electricity" question but I can't see another option

**Comment by kauansoft** [comment]
Yes i gave 777 -R to all, just restarted the vps and is working again...
