### ISSUE TITLE
Use composer

### ISSUE THREAD

**Issue by kauanguesser** [fballiano/docker-magento2#14]
How i use composer through docker container, you can show the command? i want install some modules.

Thank you.

**Comment by fballiano** [comment]
simply
docker exec -it dockermagento2_apache_1 bash
and then use composer as you would in any other machine

**Comment by kauanguesser** [comment]
Thank you

**Comment by fballiano** [comment]
no problem, it was an easy one :-)

**Comment by kauanguesser** [comment]
Working fine! Thanks... and you can check my other issue? Got an error on debian.
