### ISSUE TITLE
DB container name should be same as service name in composer file

### ISSUE THREAD

**Issue by bennythejudge** [fballiano/docker-magento2#15]
In my understanding, the hostname of a container within a compose configuration is the name of the service in the compose file.
`  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql`

Following the README to install Magento2, I found that the hostname suggest `dockermagento2_db_1` did not work for me, but `db` did.

From the [Docker doc](https://docs.docker.com/compose/networking/):

> For example, suppose your app is in a directory called myapp, and your docker-compose.yml looks like this:

`
version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: postgres
    ports:
      - "8001:5432"
`

>When you run docker-compose up, the following happens:
>A network called myapp_default is created.
>A container is created using web’s configuration. It joins the network myapp_default under the name web.
>A container is created using db’s configuration. It joins the network myapp_default under the name db.

I am going to submit a PR to this effect.

**Comment by fballiano** [comment]
thanks @bennythejudge, I merged your PR, sorry for the delay!
