### ISSUE TITLE
Is the mount for `.composer/auth.json` wrong?

### ISSUE THREAD

**Issue by bennythejudge** [fballiano/docker-magento2#18]
In [this line](https://github.com/fballiano/docker-magento2/blob/master/docker-compose.yml#L56) in the `docker-compose.yml` file,

should:

```
     - ~/.composer/auth.json:/root/.composer/auth.json
```

be

```
     - ~/.composer:/root/.composer
```

and `~/.composer` on the host contain a `auth.json` file (content according to [this page](https://getcomposer.org/doc/articles/http-basic-authentication.md)?

**Comment by bennythejudge** [comment]
When I tried my theory, the apache container would not start.
Could you please explain this? This is clearly not an issue other than my lack of understanding/knowledge.

**Comment by nutellinoit** [comment]
If you run composer as www-data user inside apache container, you need to link your auth file on your host to the www-data home folder

```
./yourhostauthjson.json:/var/www/.composer/auth.json
```

**Comment by LiamKarlMitchell** [comment]
It kept having errors so I just commented out the file from the docker composer config.
```
ERROR: for apache  Cannot start service apache: error while creating mount source path '/host_mnt/c/Users/megab/.composer/auth.json': mkdir /host_mnt/c/Users/megab/.composer: permission denied
ERROR: Encountered errors while bringing up the project.
```

**Comment by fballiano** [comment]
Hello everybody, the mount can be configured in many different ways (or removed completely), it really depends on how you want to use it.

I wanted to mount only the auth.json but you could mount the whole .composer directory, for the root user or the www-data user, it really depends on how you want to use it.
