### ISSUE TITLE
PHP bcmath extension is missing

### ISSUE THREAD

**Issue by rahulanand77** [fballiano/docker-magento2#19]
Hi,

When I am running magento setup, I am getting an error `missing extension PHP Extension bcmath.`. I logged into fballiano/nginx-ssl-for-magento2 container, and installed php7.0-bcmath and reloaded nginx, but when I am running `service php restart`, I am getting error **unknown service.**  

Can you give me any solution for the same?

Thanks

Rahul Anand

**Comment by Ritin** [comment]
error bcmath missing
log into the Apache container
>docker exec {continaername or ID} -it /bin/bash
>docker-php-ext-install -j(nproc) bcmath
>service apache2 restart

exit 
restart apache and Varnish containers

**Comment by fballiano** [comment]
Hello, I've updated the builds with php7.1 and bcmath, let me know if the issue is solved :-)

**Comment by rahulanand77** [comment]
I am still getting the same error even with the new deployment.

**Comment by rahulanand77** [comment]
Thanks @Ritin, that worked for me. I appreciate your help.
