### ISSUE TITLE
Run this docker ,but don't work .

### ISSUE THREAD

**Issue by patrickouc** [fballiano/docker-magento2#2]
hi ,@fballiano

![image](https://cloud.githubusercontent.com/assets/4326820/14844801/a5ffc6fe-0c8c-11e6-895c-1b0e8c11f74d.png)

Run this docker ,but don't work .
my ip:120.24.95.141
how setting url  ?

**Comment by fballiano** [comment]
http://magento.docker should automatically be routed to the apache container
but actually every /etc/hosts line pointing to localhost should.
can't try at the moment, if you can, can you tell me if it works?

**Comment by patrick4u** [comment]
run on the remote server ,
![image](https://cloud.githubusercontent.com/assets/4326820/14871023/4c6f24ce-0d11-11e6-98ae-79e3a83be548.png)
127.0.0.1 magento.dl1.newtouch.com ?

**Comment by patrick4u** [comment]
502 Bad Gateway

**Comment by patrick4u** [comment]
magento.dl1.newtouch.com   port:80

**Comment by fballiano** [comment]
sorry for the delay, is this still an issue? did you try the updated images with docker 1.12?

**Comment by fballiano** [comment]
please reopen the issue if it's still there

**Comment by alabius** [comment]
I have same error on mine too. I am using docker machine on windows 10.
