### ISSUE TITLE
Hi fballiano, my stack was keep 504 gateway timeout every where.

### ISSUE THREAD

**Issue by HitsiLent** [fballiano/docker-magento2#21]
Hi fballiano, my stack was keep 504 gateway timeout every where. even i set up
max_input_time,  max_execution_time. the file it was in the folder , but URL can not reach that,

environment:
AWS
elastic beanstalk
REDIS(AWS)
MYSQL(AWS RDS)
CDN cloudflare

the 504 time out drive me crazy, i was working on the for 1 month. some times it wait like few hours it works find.

**Comment by fballiano** [comment]
Hi, could you try the new updated version that I just released? it's much faster on my local machine and should never have a 504 anymore.

thanks!
