### ISSUE TITLE
Any tips to help speed things up?

### ISSUE THREAD

**Issue by benhtn** [fballiano/docker-magento2#22]
Hi there,
I've set this up on a macbook pro (2.8 GHz Intel Core i7, 16 GB 1600 MHz DDR3) running Docker CE (Engine: 18.06.0-ce, with 4 CPUs and 7.5GB of memory & 1GB of swap). 

In order to get through first installation I had to add this to varnish.vcl:
backend apache_1 {
    .host = "apache";
    .port = "80";
    .first_byte_timeout = 600s;
}
to prevent "Error 503 Backend fetch failed" errors.

However everything seems incredibly slow (minutes for each page load on front end, admin is unnavigable).

I have enabled Redis 
(e.g. from the Redis container I get
```
# redis-cli --scan | head -10
zc:k:792_LAYOUT_FRONTEND_STORE1_3D41D8CD98F00B204E9800998ECF8427E
zc:ti:792_CMS_INDEX_INDEX
zc:k:792_Zend_LocaleC_en_GB_currencytoname_GBP
zc:k:792_TRANSLATE_EN_GB_FRONTEND_DEFAULT_MAGENTO_LUMA_MAGENTO_CUSTOMER
zc:k:792_LAYOUT_ADMINHTML_STORE1_2PAGE_LAYOUT
zc:k:792_DICONFIG774B76ADE48691A57FBFC9E80B5A99CD
zc:k:792_Zend_LocaleC_en_GB_parentlocale_
zc:k:792_Zend_LocaleC_en_US_parentlocale_
zc:k:792_LAYOUT_FRONTEND_STORE1_3
zc:k:792_DB_IS_UP_TO_DATE
```
)

However it doesn't look like varnish is working properly (I am seeing no signs of caching in the response headers).   

Any ideas/ further info I can provide to help figure out why it's running so slowly please?

Many thanks
Ben

**Comment by fballiano** [comment]
I've updated the project with some speed optimizations, based on the different "consistency" values supported by docker, it should be now much much faster.
