### ISSUE TITLE
Suitable for production deployment in swarm mode?

### ISSUE THREAD

**Issue by vimal0777** [fballiano/docker-magento2#28]
Hello,  @fballiano thank you for this repo . This stack is the best that we found for swarm mode ready deployment. How ever , is this suitable for production environments? We are planning to deploy this with Traefik reverse proxy in a  3 node cluster.

**Comment by fballiano** [comment]
Thanks a lot for the kind words :-)

I've to tell you that I've never used this configurations in productions (never had the chance to use a docker based production system actually) thus I really don't know what to tell you about this :-(
