### ISSUE TITLE
An abstract factory could not create an instance

### ISSUE THREAD

**Issue by rolandalla** [fballiano/docker-magento2#32]
`An abstract factory could not create an instance of magentoframeworkencryptionencryptor(alias: Magento\Framework\Encryption\Encryptor).`

**Comment by fballiano** [comment]
that's a bug which was introduced by magento 2.3.2, I'm already solving it upgrading libsodium... but that's a bad implementation by magento

**Comment by rolandalla** [comment]
You are right , saw that on 2.3.2 worked by updating libsodium to a >1.0.13*

**Comment by fballiano** [comment]
exactly, I'm updating the docker image but it seems docker hub is having troubles today...

**Comment by rolandalla** [comment]
Thanks for fast reply , will check the new Image tomorrow

**Comment by fballiano** [comment]
it seems that finally docker hub rebuilt the image and the libsodium is now updated, can you pull the new image?

**Comment by rolandalla** [comment]
Em another error now ....Warning: `Use of undefined constant SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13 - assumed 'SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13' (this will throw an Error in a future version of PHP) in /var/www/html/vendor/magento/framework/Encryption/Encryptor.php on line 153`

**Comment by fballiano** [comment]
mmm if there's an undefined constant there's nothing I can do about that. I don't get the error thou. are you in development mode?

**Comment by rolandalla** [comment]
Yes , I was in development mode . But it is a new magento project . Today I am out of office. Will check it tomorrow, maybe I was In harry :/ and did something wrong .
Will let you know

**Comment by fballiano** [comment]
thanks

**Comment by rolandalla** [comment]
Just tested again, my mistake ..is working now :)
