### ISSUE TITLE
bind source path does not exist

### ISSUE THREAD

**Issue by Umair-Ansari** [fballiano/docker-magento2#33]
I am trying to configure but getting this error

> 
> vagrant_data_db_1 is up-to-date
> vagrant_data_cache_1 is up-to-date
> vagrant_data_sessions_1 is up-to-date
> vagrant_data_clusterdata_1 is up-to-date
> Creating vagrant_data_apache_1 ... error
> 
> ERROR: for vagrant_data_apache_1  Cannot create container for service apache: invalid mount config for type "bind": bind source path does not exist
> 
> ERROR: for apache  Cannot create container for service apache: invalid mount config for type "bind": bind source path does not exist
> ERROR: Encountered errors while bringing up the project.
>

**Comment by fballiano** [comment]
do you have magento in the "magento2" directory, right next to the docker-compose file?

**Comment by Umair-Ansari** [comment]
That was my mistake, but after I place folder "magento2" right beside I got another error 

> Creating vagrant_data_cache_1       ... done
Creating vagrant_data_db_1          ... done
Creating vagrant_data_clusterdata_1 ... done
Creating vagrant_data_sessions_1    ... done
    app: Creating vagrant_data_apache_1      ...
Creating vagrant_data_apache_1      ... done
    app: Creating vagrant_data_varnish_1     ...
Creating vagrant_data_varnish_1     ... error
    app:
    app: ERROR: for vagrant_data_varnish_1  Cannot start service varnish: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely"
    app:
    app:
    app: ERROR: for varnish  Cannot start service varnish: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely"
    app:
    app: Encountered errors while bringing up the project.
