### ISSUE TITLE
eMailing and db backup?

### ISSUE THREAD

**Issue by hasanr68** [fballiano/docker-magento2#36]
Hi all.

Got this setup implemented. However, system email (transactions, forgot password) don't work. It would be great to have the following also:

1. eMail setup (maybe php) + smtp.
2. Database backups.

Any suggestions?

**Comment by fballiano** [comment]
Hi @hasanr68,
1. you can use any smtp mudule for magento2 or mailchimp/mandrill or anything ;-)
2. you can ssh the DB container and mysqldump or (better) back up directly the DB container ;-) but that's a little bit outside the scope of the project, it's more related to docker sysadmin
