### ISSUE TITLE
The requested PHP extension sockets is missing from your system.

### ISSUE THREAD

**Issue by AnonJervis** [fballiano/docker-magento2#38]
I have an Ubuntu18.04 server on VM and got PHP extension sockets failed during magento2 installation readiness checklist. 

![php extension sockets](https://user-images.githubusercontent.com/59471184/74138686-03403400-4c2d-11ea-9063-ac06993fd21d.jpeg)

How can I resolve this? 

Edit: Some of the stuff became irrelevant and I changed my post to pinpoint issue better.

**Comment by AnonJervis** [comment]
I have solved this issue. I'll leave it here so hopefully it may help others.

After you ```docker-compose up -d``` ,

```docker exec -it your_apache_container /bin/bash``` and execute:

```
docker-php-ext-install sockets
docker-php-ext-configure sockets
docker-php-ext-enable sockets  (optional don't know if that helps)
```

Once that's done, exit container and execute:

```docker-compose restart ```

That should get you pass magento2 readiness page.

**Comment by AnonJervis** [comment]
This problem arises again when I need to install extensions through web wizard readiness check. Reopening this hopefully someone can chip in.

**Comment by sirbob** [comment]
@AnonJervis - docker-compose uses this apache image: https://github.com/fballiano/docker-magento2-apache-php/blob/master/Dockerfile (https://hub.docker.com/r/fballiano/magento2-apache-php).
I guess you could fork it and add `socket` there. Then modify docker-compose.yml to use your modified forked Dockerfile/image.

**Comment by fballiano** [comment]
sorry guys, I fixed the image now!
