### ISSUE TITLE
Installation stuck on database connection step 2, incorrect documentation

### ISSUE THREAD

**Issue by nasl** [fballiano/docker-magento2#40]
Server host localhost -> getting error  SQLSTATE[HY000] [2002] No such file or directory 
Server host 127.0.0.1 -> getting error SQLSTATE[HY000] [2002] Connection refused
Server host mariadb -> getting error SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known 
Server host docker-magento2_db_1 -> getting error SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
Server host deab688c09af -> OK!
Server host magento2_db_1 -> OK!

There is a line in documentation, but it is incorrect: instead of docker-magento2_db_1 it has to be magento2_db_1

**Comment by fballiano** [comment]
it's better if you install magento via command line (I'll add it to the doc now) but also, on my mac the host names are correct.
