### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by nasl** [fballiano/docker-magento2#41]
> docker exec -it dockermagento2_apache_1 bash
> php bin/magento dev:source-theme:deploy
> php bin/magento setup:static-content:deploy

it should be 

> docker exec -it **magento2**_apache_1 bash
> php bin/magento dev:source-theme:deploy
> php bin/magento setup:static-content:deploy

**Comment by fballiano** [comment]
it's actually different for me, it is docker-magento2_apache_1, at least with latest version of docker-desktop for mac
