### ISSUE TITLE
Magento 2.4 require ElasticSearch

### ISSUE THREAD

**Issue by ilevennet** [fballiano/docker-magento2#44]
The new Magento 2.4 require ElasticSearch mandatory for installation.

A new ElasticSearch Container should be added for this purpose in your project.

See: https://devdocs.magento.com/guides/v2.4/install-gde/bk-install-guide.html

**Comment by fballiano** [comment]
thanks for the suggestion, I'm working on it!

In the meanwhile I've created some tags in the repo, so the new version will be available in the M2.4 tag

**Comment by fballiano** [comment]
I think it should be ready in https://github.com/fballiano/docker-magento2/blob/M2.4

**Comment by peppelauro** [comment]
Link is broken, maybe you mean: https://github.com/fballiano/docker-magento2/tree/M2.4

**Comment by matthews52180** [comment]
The apache container has php 7.2 installed instead of 7.4 right?

**Comment by fballiano** [comment]
noup, on the 2.4 branch it has 7.4

did you docker-compose pull?

**Comment by matthews52180** [comment]
hey I am sorry wrong version everything is great. Thank you :)

**Comment by fballiano** [comment]
:-)
