### ISSUE TITLE
502 Bad Gateway on certain requests

### ISSUE THREAD

**Issue by bryanruiz** [fballiano/docker-magento2#7]
I've got a pretty much clean install of these 5 or so containers using docker-compose, and have magento2 installed, but every third request or so I'm getting 502 Bad Gateway because of a connection that was reset by apache.  This happens occasionally on random requests.

I'm going to enable developer mode and see if I can find any more information.   No extensions or code customizations at this point have been implemented.

UPDATE (found this right when it happens):

varnish_1      | Child (17) died signal=6 (core dumped)
varnish_1      | Child (17) Panic message:
varnish_1      | Assert error in vbf_fetch_thread(), cache/cache_fetch.c line 842:
varnish_1      |   Condition(uu == bo->fetch_obj->len) not true.
varnish_1      | thread = (cache-worker)
varnish_1      | ident = Linux,4.4.0-71-generic,x86_64,-smalloc,-smalloc,-hcritbit,epoll
varnish_1      | Backtrace:
varnish_1      |   0x4330a8: varnishd() [0x4330a8]
varnish_1      |   0x421025: varnishd() [0x421025]
varnish_1      |   0x435cdc: varnishd(Pool_Work_Thread+0x39c) [0x435cdc]
varnish_1      |   0x44912c: varnishd() [0x44912c]
varnish_1      |   0x7fbe94c200a4: /lib/x86_64-linux-gnu/libpthread.so.0(+0x80a4) [0x7fbe94c200a4]
varnish_1      |   0x7fbe9495587d: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fbe9495587d]
varnish_1      |   busyobj = 0x7fbe8346c020 {
varnish_1      |     ws = 0x7fbe8346c0e0 {
varnish_1      |       id = "bo",
varnish_1      |       {s,f,r,e} = {0x7fbe8346e008,+864,(nil),+57368},

Here is a varnish ticket addressing the issue.. https://www.varnish-cache.org/trac/ticket/1596

**Comment by bryanruiz** [comment]
upgraded to varnish 4.1 and this fixed the issue i believe...   removed "-u varnish" from start.sh

**Comment by fballiano** [comment]
Hi and thanks for the report!
only removing the "-u varnish" wasn't enough?

cause debian jessie doesn't have varnish 4.1 so I'll have to see how to handle the change.

**Comment by fballiano** [comment]
ok I managed to update the containers to varnish 4.1 (docker hub just finished rebuilding everything), could you please give it a try?

thanks a lot!

**Comment by fballiano** [comment]
closed for no feedback, but I think it's fixed but the update
